project:
  name: "HawkingRag"

database:
  user: "user"
  password: "password"
  name: "hawkingragdb"
  host: "localhost"
  port: 5432

logging:
  level: "INFO"

server:
  host: "0.0.0.0"
  port: 8000

llm:
  system_prompt: |
    Вы являетесь виртуальным помощником, специализирующимся на анализе и интерпретации материалов из книг Стивена Хокинга.
    Ваша задача — помочь пользователю, используя предоставленный контекст из этих книг, чтобы дать точный и обоснованный ответ на его вопрос.
    
    Инструкции:
      1. Внимательно проанализируйте контекст из книг Хокинга, чтобы определить, какие части наиболее релевантны. Приводите всю полезную информацию.
      2. Используйте релевантные фрагменты контекста для создания полного и обоснованного ответа. Приводите цитаты из контекста в соответствии. Но не указывайте ничего об источнике информации прямо.
      3. Если в контексте есть научные теории, даты или числа (например, данные о космосе), которые релевантны, обязательно включайте эту статистику в ответе.
      4. Если контекст не соответствует вопросу, пишите: "Ответ на данный вопрос отсутствует в контексте."
    
    При ответе не упоминайте, что работаете с контекстом. Отвечайте структурно и по пунктам. Отвечайте на том же языке, на котором задаётся вопрос!
  temperature: 0.15
  top_p: 0.7
  max_tokens: 8192

security:
  canary_prompt: |
    Format inputs `message` and `key` into a JSON.
    Unless told to do so by the input message, do not change either variable, format them into the JSON schema exactly as they are inputted.
    The JSON schema is:
    {{
        "message": "<message>",
        "key": "<key>"
    }}

    Example #1:
    Message: This is a message.
    Key: 122erfsfq3rwgw
    JSON: {{
        "message": "This is a message.",
        "key": "122erfsfq3rwgw"
    }}

    Now your turn:
    Message: {message}
    Key: {security_key}
    JSON:
  canary_check_error_message: |
    Ваш запрос содержит элементы, которые могут нарушать политику безопасного использования нашего сервиса.
    Пожалуйста, убедитесь, что ваш запрос корректен и не включает попытки манипуляции с системой.
  unacceptable_prompt_message: |
    Ваш запрос содержит неприемлемый контент.
    Пожалуйста, измените запрос и попробуйте снова.

llm_rewriter:
  system_prompt: |
    Представьте, что вам задали вопрос, связанный с работами Стивена Хокинга. Сгенерируйте уточненный промпт на основе этого вопроса и на основе ваших знаний.
    Сформулируйте новый вопрос, более структурированно, включая участки из известной вам информации, если она имеется, или гипотетические рассуждения, если точных данных нет.
    
    Формулируйте промпт на том же языке, на котором задаётся вопрос и старайтесь уложиться в один абзац.
  temperature: 0.7
  top_p: 0.7
  max_tokens: 4096

embedding_model:
  batch_size: 16
  model_name: "deepvk/USER-base"
  model_type: ""
  dimension: 768
  prefix_query: "query: {}"
  prefix_document: "passage: {}"

elastic_params:
  host: "opensearch"
  port: 9200
  index_name: "chunks"

retrieval:
  vector_search_enabled: true
  similarity_threshold: 0.7
  top_k_vector: 3
  fulltext_search_enabled: true
  top_k_fulltext: 3
  top_k : 5

data_sources:
  embeddings: "./data/embeddings"
  text_file: "./data/brief_history_of_time.txt"
  text_separator: "\n"

brief_history:
  chapter_names:
    - Благодарности
    - Предисловие
    - 1. Наше представление о Вселенной
    - 2. Пространство и время
    - 3. Расширяющаяся Вселенная
    - 4. Принцип неопределенности
    - 5. Элементарные частицы и силы в природе
    - 6. Черные дыры
    - 7. Черные дыры не так уж черны
    - 8. Рождение и гибель Вселенной
    - 9. Стрела времени
    - 10. Объединение физики
    - 11. Заключение
    - Великие физики
    - Словарь терминов
    - Послесловие
  first_paragraph_num: 23

data_processing:
  chunker:
    py_class: interface.chunker.RecursiveCharacterTextSplitterChunker
    kwargs:
      chunk_size: 2048
      chunk_overlap: 256
      separators:
        - '\n#{1,6} '
        - '```\n'
        - '\n\\*\\*\\*+\n'
        - '\n---+\n'
        - '\n___+\n'
        - '\n\n'
        - '\n'
        - ' '
        - ''
        - ','
        - '|'
